'use client';
import React, { useState } from 'react';
import { Sparkles, Image, FileText, ChevronDown, Download, Copy, RefreshCw, Loader2 } from 'lucide-react';

const WRITING_TEMPLATES = [
  { id: 'bio', label: 'Artist Bio', desc: 'Professional bio for press kits and profiles' },
  { id: 'press', label: 'Press Release', desc: 'Announce a new release or milestone' },
  { id: 'caption', label: 'Social Captions', desc: 'Instagram, Twitter, TikTok copy' },
  { id: 'pitch', label: 'Pitch Letter', desc: 'Reach out to sync supervisors and labels' },
  { id: 'grant', label: 'Grant Application', desc: 'Apply for music development grants' },
  { id: 'song_desc', label: 'Song Description', desc: 'Metadata and streaming descriptions' },
  { id: 'interview', label: 'Interview Prep', desc: 'Talking points for press interviews' },
];

const IMAGE_TOOLS = ['DALL-E 3', 'Stable Diffusion', 'Adobe Firefly'];
const IMAGE_USAGES = ['Album Cover', 'Event Flyer', 'Social Post', 'Banner', 'Artist Photo Background'];
const STYLE_CHIPS = ['Cinematic', 'Dark', 'Neon', 'Minimal', 'Abstract', 'Vintage', 'Urban', 'Dreamy', 'Raw', 'Professional'];

export default function AIStudioPage() {
  const [tab, setTab] = useState<'image' | 'writing' | 'history'>('image');
  const [imageTool, setImageTool] = useState('DALL-E 3');
  const [imageUsage, setImageUsage] = useState('Album Cover');
  const [prompt, setPrompt] = useState('');
  const [styles, setStyles] = useState<string[]>([]);
  const [generating, setGenerating] = useState(false);
  const [writingTemplate, setWritingTemplate] = useState(WRITING_TEMPLATES[0]);
  const [writingInput, setWritingInput] = useState('');
  const [writingOutput, setWritingOutput] = useState('');
  const [writingLoading, setWritingLoading] = useState(false);
  const credits = 12;

  const toggleStyle = (s: string) => setStyles(prev => prev.includes(s) ? prev.filter(x => x !== s) : [...prev, s]);

  const handleGenerate = () => {
    setGenerating(true);
    setTimeout(() => setGenerating(false), 2500);
  };

  const handleWriting = () => {
    setWritingLoading(true);
    setTimeout(() => {
      setWritingOutput(`[AI-generated ${writingTemplate.label} based on your input: "${writingInput}"]\n\nThis would be your professionally crafted content generated by Claude. Connect your ANTHROPIC_API_KEY in Vercel environment variables to enable live generation.`);
      setWritingLoading(false);
    }, 1800);
  };

  return (
    <div className="p-8 md:p-12 space-y-8 max-w-6xl">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-white uppercase italic">AI Creative Studio.</h1>
          <p className="text-sm text-gray-500 font-medium mt-1">Generate images and write professional content with AI.</p>
        </div>
        <div className="flex items-center gap-2 bg-amber-500/10 border border-amber-500/20 px-4 py-2 rounded-xl">
          <Sparkles className="w-4 h-4 text-amber-400" />
          <span className="text-amber-400 font-bold text-sm">{credits} credits</span>
        </div>
      </div>

      {/* TABS */}
      <div className="flex gap-1 bg-white/5 p-1 rounded-xl w-fit">
        {(['image', 'writing', 'history'] as const).map(t => (
          <button key={t} onClick={() => setTab(t)}
            className={`px-6 py-2.5 rounded-lg text-xs font-bold uppercase tracking-widest transition-all ${
              tab === t ? 'bg-white text-black' : 'text-gray-400 hover:text-white'
            }`}>
            {t === 'image' ? 'Image Creator' : t === 'writing' ? 'Writing Tools' : 'My Creations'}
          </button>
        ))}
      </div>

      {/* IMAGE CREATOR */}
      {tab === 'image' && (
        <div className="grid grid-cols-1 lg:grid-cols-5 gap-8">
          <div className="lg:col-span-2 space-y-6">
            {/* Tool selector */}
            <div className="space-y-2">
              <label className="text-[10px] font-bold text-gray-500 uppercase tracking-widest">AI Tool</label>
              <div className="grid grid-cols-3 gap-2">
                {IMAGE_TOOLS.map(t => (
                  <button key={t} onClick={() => setImageTool(t)}
                    className={`py-2 px-3 rounded-lg text-[10px] font-bold uppercase tracking-wider transition-all border ${
                      imageTool === t ? 'bg-[#A855F7] text-white border-[#A855F7]' : 'border-white/10 text-gray-500 hover:text-white hover:border-white/20'
                    }`}>
                    {t === 'DALL-E 3' ? 'DALL·E 3' : t}
                  </button>
                ))}
              </div>
            </div>

            {/* Usage */}
            <div className="space-y-2">
              <label className="text-[10px] font-bold text-gray-500 uppercase tracking-widest">Usage Type</label>
              <select value={imageUsage} onChange={e => setImageUsage(e.target.value)}
                className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-3 text-sm text-white focus:outline-none focus:border-[#A855F7]">
                {IMAGE_USAGES.map(u => <option key={u} className="bg-[#111]">{u}</option>)}
              </select>
            </div>

            {/* Prompt */}
            <div className="space-y-2">
              <label className="text-[10px] font-bold text-gray-500 uppercase tracking-widest">Prompt</label>
              <textarea value={prompt} onChange={e => setPrompt(e.target.value)} rows={4}
                placeholder={`Describe your ${imageUsage.toLowerCase()}. Example: "Late night R&B vibes, moody blue lighting, close-up portrait, cinematic quality..."`}
                className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-3 text-sm text-white focus:outline-none focus:border-[#A855F7] resize-none"
              />
            </div>

            {/* Style chips */}
            <div className="space-y-2">
              <label className="text-[10px] font-bold text-gray-500 uppercase tracking-widest">Style Modifiers</label>
              <div className="flex flex-wrap gap-2">
                {STYLE_CHIPS.map(s => (
                  <button key={s} onClick={() => toggleStyle(s)}
                    className={`px-3 py-1 rounded-full text-[10px] font-bold uppercase tracking-wider transition-all border ${
                      styles.includes(s) ? 'bg-[#A855F7] text-white border-[#A855F7]' : 'border-white/10 text-gray-500 hover:border-white/30 hover:text-white'
                    }`}>
                    {s}
                  </button>
                ))}
              </div>
            </div>

            <button onClick={handleGenerate} disabled={!prompt || generating}
              className="w-full py-4 rounded-xl bg-[#A855F7] text-white font-bold text-xs uppercase tracking-widest hover:bg-[#00B8E0] transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2 shadow-lg shadow-[#A855F7]/20">
              {generating ? <><Loader2 className="w-4 h-4 animate-spin" /> Generating...</> : <><Sparkles className="w-4 h-4" /> Generate (1 credit)</>}
            </button>
          </div>

          {/* Results grid */}
          <div className="lg:col-span-3">
            <div className="grid grid-cols-2 gap-4">
              {Array.from({ length: 4 }).map((_, i) => (
                <div key={i} className="aspect-square bg-[#111] border border-white/5 rounded-2xl flex items-center justify-center relative group overflow-hidden">
                  {generating ? (
                    <Loader2 className="w-8 h-8 text-white/20 animate-spin" />
                  ) : (
                    <div className="text-center space-y-2 p-6">
                      <Image className="w-8 h-8 text-white/10 mx-auto" />
                      <p className="text-[10px] text-gray-700 font-medium">Generation {i + 1}</p>
                    </div>
                  )}
                  {!generating && (
                    <div className="absolute inset-0 bg-black/70 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center gap-3">
                      <button className="p-2 bg-white/10 rounded-lg hover:bg-white/20 transition-all"><Download className="w-4 h-4 text-white" /></button>
                      <button className="p-2 bg-white/10 rounded-lg hover:bg-white/20 transition-all"><RefreshCw className="w-4 h-4 text-white" /></button>
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* WRITING TOOLS */}
      {tab === 'writing' && (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          <div className="space-y-2">
            {WRITING_TEMPLATES.map(t => (
              <button key={t.id} onClick={() => setWritingTemplate(t)}
                className={`w-full text-left p-4 rounded-xl border transition-all ${
                  writingTemplate.id === t.id ? 'bg-[#A855F7]/10 border-[#A855F7]/30 text-white' : 'border-white/5 text-gray-400 hover:text-white hover:border-white/10 bg-[#111]'
                }`}>
                <p className="text-xs font-bold">{t.label}</p>
                <p className="text-[10px] text-gray-500 mt-0.5">{t.desc}</p>
              </button>
            ))}
          </div>
          <div className="lg:col-span-2 space-y-4">
            <div className="space-y-2">
              <label className="text-[10px] font-bold text-gray-500 uppercase tracking-widest">Tell us about your project</label>
              <textarea value={writingInput} onChange={e => setWritingInput(e.target.value)} rows={5}
                placeholder={`Describe what you need for your ${writingTemplate.label.toLowerCase()}...`}
                className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-3 text-sm text-white focus:outline-none focus:border-[#A855F7] resize-none"
              />
            </div>
            <button onClick={handleWriting} disabled={!writingInput || writingLoading}
              className="px-8 py-3 rounded-xl bg-[#A855F7] text-white font-bold text-xs uppercase tracking-widest hover:bg-[#00B8E0] transition-all disabled:opacity-50 flex items-center gap-2">
              {writingLoading ? <><Loader2 className="w-4 h-4 animate-spin" /> Writing...</> : <><FileText className="w-4 h-4" /> Generate</>}
            </button>
            {writingOutput && (
              <div className="bg-[#111] border border-white/10 rounded-2xl p-6 relative">
                <pre className="text-sm text-gray-300 whitespace-pre-wrap font-sans leading-relaxed">{writingOutput}</pre>
                <button onClick={() => navigator.clipboard.writeText(writingOutput)}
                  className="absolute top-4 right-4 p-2 bg-white/5 rounded-lg hover:bg-white/10 transition-all">
                  <Copy className="w-4 h-4 text-gray-400" />
                </button>
              </div>
            )}
          </div>
        </div>
      )}

      {/* HISTORY */}
      {tab === 'history' && (
        <div className="text-center py-20 border border-dashed border-white/10 rounded-2xl">
          <Sparkles className="w-12 h-12 text-white/10 mx-auto mb-4" />
          <p className="text-gray-500 font-medium">Your AI generations will appear here.</p>
        </div>
      )}
    </div>
  );
}


